name: Analyze Code

on:
  push:
    paths: 
      - "**.dart"
      - ".github/workflows/analyze-dart.yml"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths: 
      - "**.dart"
      - ".github/workflows/analyze-dart.yml"

jobs:
  build:
    name: "Static analysis & format check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Generate files with Builder
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Analyze code
        uses: ValentinVignal/action-dart-analyze@v0.16
        with:
          fail-on: warning
